### PR TITLE
#49 Added new rules that drop all rows without weather data and did n…

### PR DESCRIPTION
**Pull request by rectheworld**
---
name: Added new rules that drop all rows without weather data and did not drop noaa stations not in the US
---

# High Level Changes
1.1-circles-to-many-noaa-stations-usa-weather-data.ipynb was producing a file that drops rows based on if they are missing min temp, I have updated the file to drop rows only if they are missing ALL the weather elements.  It also no longer drops mated stations that are outside the US. 

# Necessary Details
The resulting file is 109, 624 rows down

### CODE REVIEW

**Comment by ijd5004** [comment]
<p>One part of the code that looks like it was removed was checking for US stations only. Are we still doing that?</p><p> </p><p>Also, I don't think I realized we were initially getting over 1 million matches, before the screening.</p>

**Comment by ijd5004** [comment]
<p>Also, if we bring that line back over that checks for US stations, we should make sure it works. I think I tried it on my notebook and I remember some CA stations slipping through</p><p> </p>

**Comment by rectheworld** [comment]
The input data only includes circles from the CBC that are in the United States. But it’s possible for those American circles to be matched with a closest station that is not in the United States. In this version of the notebook we keep those stations that are not in the United States. Do you think that should be adjusted?

**Comment by ijd5004** [comment]
<p>No. I agree they should be kept.</p><p> </p><p>Everything else looks good!</p>

**Pull request merged**
